### ISSUE TITLE
Slow Splash Screen Dismissal

### ISSUE THREAD

**Issue by PasanSWijekoon** [PasanSWijekoon/UMeeChat-App-FrontEnd#12]
Splash screen dismissal might be delayed if font loading fails or if there's a network issue.

**Comment by david-solomon-henshaw** [comment]
@PasanSWijekoon  if i understand correctly what you mean is the splash screen dismissal is delayed due to network issues or if the font loading fails. which means you don't want the splash screen dismissal to be dependent on any of this scenarios but its dismissal should be independent is that right ?

**Comment by PasanSWijekoon** [comment]
Yeah I am closing this issue
